# 02_cluster_profiling

- Done By: Kedar Raju Pawar
- date:2026-02-25 time: 18:16:00

In [1]:
import pandas as pd

## 02_A_Hardware_Based_Cluster_Profiling

#### 1.  Load dataset

In [14]:
df_hardware=pd.read_csv ('hardware_clustered_laptops.csv')
df_hardware.columns

Index(['Company', 'laptop_type', 'screen_size_inch',
       'display_resolution_width', 'display_resolution_height', 'panel_type',
       'is_touchscreen', 'resolution_class', 'cpu_brand', 'cpu_family',
       'cpu_generation', 'clock_speed_ghz', 'cpu_tier', 'gpu_brand', 'ram_gb',
       'ssd_gb', 'hdd_gb', 'flash_gb', 'hybrid_gb', 'total_storage_gb',
       'weight_kg', 'weight_class', 'price_band', 'Price', 'is_price_outlier',
       'cpu_tier_numeric', 'ssd_indicator', 'hardware_cluster', 'cluster'],
      dtype='object')

#### 2. Compute Cluster Means

In [41]:
hardwar_cluster_profile = df_hardware.groupby("cluster").agg({
    "Price": "mean",
    "ram_gb": "mean",
    "total_storage_gb": "mean",
    "cpu_tier_numeric": "mean",
    "ssd_indicator": "mean"
}).round(2)

hardwar_cluster_profile

            Price  ram_gb  total_storage_gb  cpu_tier_numeric  ssd_indicator
cluster
0        76739.23    9.51            413.33              4.14           0.82
1        67827.05   10.63           1126.59              4.36           0.54
2        49575.89    6.67            308.21              3.54           0.72

#### 3. Add Distribution Insights

##### CPU Tier Distribution

In [12]:
pd.crosstab(df_hardware["cluster"], df_hardware["cpu_tier_numeric"], normalize="index")

cpu_tier_numeric         1         2         3         4         5
cluster
0                 0.088889  0.000000  0.088889  0.325926  0.496296
1                 0.021680  0.016260  0.121951  0.265583  0.574526
2                 0.185484  0.018145  0.120968  0.421371  0.254032

##### Brand Dominance

In [15]:
pd.crosstab(df_hardware["cluster"], df_hardware["Company"], normalize="index")

Company,ACER,APPLE,ASUS,CHUWI,DELL,FUJITSU,GOOGLE,HP,HUAWEI,LENOVO,LG,MEDIACOM,MICROSOFT,MSI,RAZER,SAMSUNG,TOSHIBA,VERO,XIAOMI
cluster,,,,,,,,,,,,,,,,,,,
0,0.066667,0.000000,0.074074,0.000000,0.303704,0.000000,0.022222,0.170370,0.000000,0.237037,0.014815,0.007407,0.044444,0.000000,0.007407,0.014815,0.037037,0.000000,0.000000
1,0.070461,0.008130,0.184282,0.000000,0.287263,0.002710,0.000000,0.149051,0.000000,0.197832,0.000000,0.000000,0.000000,0.084011,0.005420,0.002710,0.008130,0.000000,0.000000
2,0.098790,0.028226,0.096774,0.006048,0.181452,0.004032,0.000000,0.215726,0.004032,0.252016,0.002016,0.012097,0.000000,0.006048,0.004032,0.010081,0.066532,0.004032,0.008065

##### Touchscreen %

In [16]:
df_hardware.groupby("cluster")["is_touchscreen"].mean()

cluster
0    1.0000
1    0.0271
2    0.0000
Name: is_touchscreen, dtype: float64

#### 4 Build Profile Table

In [45]:
hardware_profile=(
        df_hardware.groupby("cluster")
        .agg({
            "Price": "mean",
            "ram_gb": "mean",
            "total_storage_gb": "mean",
            "cpu_tier_numeric": "mean",
            "is_touchscreen": "mean"
        })
        .round(2)
        .reset_index()
)
hardware_profile.columns=[
        "Clusters",
        "Avg Price",
        "Avg Ram(GB)",
        "Avg Storage (GB)",
        "Avg CPU_tier_Numeric",
        "Avg TouchScreen"
    ]
hardware_profile

,Clusters,Avg Price,Avg Ram(GB),Avg Storage (GB),Avg CPU_tier_Numeric,Avg TouchScreen
0,0,76739.23,9.51,413.33,4.14,1.00
1,1,67827.05,10.63,1126.59,4.36,0.03
2,2,49575.89,6.67,308.21,3.54,0.00

In [46]:
hardware_profile["Segment Name"] = [
    "Premium Touch Ultrabooks",
    "Storage-Focused Productivity",
    "Entry-Level Budget"
]
hardware_profile = hardware_profile.sort_values("Avg Price")
hardware_profile

,Clusters,Avg Price,Avg Ram(GB),Avg Storage (GB),Avg CPU_tier_Numeric,Avg TouchScreen,Segment Name
2,2,49575.89,6.67,308.21,3.54,0.00,Entry-Level Budget
1,1,67827.05,10.63,1126.59,4.36,0.03,Storage-Focused Productivity
0,0,76739.23,9.51,413.33,4.14,1.00,Premium Touch Ultrabooks

#### conclusion:

- Although Cluster 1 has slightly stronger raw specifications (RAM and CPU tier), Cluster 0 commands higher pricing due to premium features such as touchscreen and likely lightweight design.

- This indicates that in this dataset, user experience and design features contribute significantly to price positioning, sometimes more than raw hardware capacity.

##### Cluster 0 — Premium Touch Ultrabooks

- Highest average price (~₹76K)

- 100% touchscreen penetration

- Strong CPU tier

- SSD-dominant configuration

- This segment represents premium ultrabooks emphasizing portability, touchscreen experience, and balanced high-end performance.

##### Cluster 1 — Storage-Focused Productivity



- Mid-range price (~₹67K)

- Highest average storage capacity

- Strong CPU tier

- Minimal touchscreen presence

- This cluster appears optimized for productivity users requiring large storage capacity rather than premium design features.

##### Cluster 2 — Entry-Level Budget

- Lowest average price (~₹49K)

- Lowest RAM and CPU tier

- No touchscreen presence

- Moderate SSD penetration

- This segment represents cost-sensitive consumers prioritizing affordability over performance and premium features.

## 02_B_Market_Based_Cluster_Profiling

#### 1. Load Dataset

In [47]:
df_market=pd.read_csv ('Market_clustered_laptops.csv')
df_market.columns

Index(['Company', 'laptop_type', 'screen_size_inch',
       'display_resolution_width', 'display_resolution_height', 'panel_type',
       'is_touchscreen', 'resolution_class', 'cpu_brand', 'cpu_family',
       'cpu_generation', 'clock_speed_ghz', 'cpu_tier', 'gpu_brand', 'ram_gb',
       'ssd_gb', 'hdd_gb', 'flash_gb', 'hybrid_gb', 'total_storage_gb',
       'weight_kg', 'weight_class', 'price_band', 'Price', 'is_price_outlier',
       'cpu_tier_numeric', 'ssd_indicator', 'hardware_cluster', 'cluster',
       'Market_cluster'],
      dtype='object')

#### 2. Compute Cluster Means

In [49]:
market_cluster_profile = (
    df_market.groupby("cluster")
    .agg({
        "Price": "mean",
        "ram_gb": "mean",
        "total_storage_gb": "mean",
        "cpu_tier_numeric": "mean",
        "ssd_indicator": "mean",
        "is_touchscreen": "mean"
    })
    .round(2)
    .reset_index()
)

market_cluster_profile

,cluster,Price,ram_gb,total_storage_gb,cpu_tier_numeric,ssd_indicator,is_touchscreen
0,0,76739.23,9.51,413.33,4.14,0.82,1.00
1,1,67827.05,10.63,1126.59,4.36,0.54,0.03
2,2,49575.89,6.67,308.21,3.54,0.72,0.00

#### 3 Add Distribution Insights

##### CPU Tier Distribution

In [50]:
pd.crosstab(
    df_market["cluster"],
    df_market["cpu_tier_numeric"],
    normalize="index"
)

cpu_tier_numeric         1         2         3         4         5
cluster
0                 0.088889  0.000000  0.088889  0.325926  0.496296
1                 0.021680  0.016260  0.121951  0.265583  0.574526
2                 0.185484  0.018145  0.120968  0.421371  0.254032

##### Brand Distribution

In [51]:
pd.crosstab(
    df_market["cluster"],
    df_market["Company"],
    normalize="index"
)

Company,ACER,APPLE,ASUS,CHUWI,DELL,FUJITSU,GOOGLE,HP,HUAWEI,LENOVO,LG,MEDIACOM,MICROSOFT,MSI,RAZER,SAMSUNG,TOSHIBA,VERO,XIAOMI
cluster,,,,,,,,,,,,,,,,,,,
0,0.066667,0.000000,0.074074,0.000000,0.303704,0.000000,0.022222,0.170370,0.000000,0.237037,0.014815,0.007407,0.044444,0.000000,0.007407,0.014815,0.037037,0.000000,0.000000
1,0.070461,0.008130,0.184282,0.000000,0.287263,0.002710,0.000000,0.149051,0.000000,0.197832,0.000000,0.000000,0.000000,0.084011,0.005420,0.002710,0.008130,0.000000,0.000000
2,0.098790,0.028226,0.096774,0.006048,0.181452,0.004032,0.000000,0.215726,0.004032,0.252016,0.002016,0.012097,0.000000,0.006048,0.004032,0.010081,0.066532,0.004032,0.008065

##### Touchscreen Ratio

In [52]:
df_market.groupby("cluster")["is_touchscreen"].mean()

cluster
0    1.0000
1    0.0271
2    0.0000
Name: is_touchscreen, dtype: float64

#### 4.Build Final Profile Table

In [56]:
market_profile = (
    df_market.groupby("cluster")
    .agg({
        "Price": "mean",
        "ram_gb": "mean",
        "total_storage_gb": "mean",
        "cpu_tier_numeric": "mean",
        "is_touchscreen": "mean"
    })
    .round(2)
    .reset_index()
)

market_profile.columns = [
    "Cluster",
    "Avg Price",
    "Avg RAM (GB)",
    "Avg Storage (GB)",
    "Avg CPU Tier",
    "Touchscreen Ratio"
]

market_cluster_profile = market_profile.sort_values("Avg Price")

market_cluster_profile

,Cluster,Avg Price,Avg RAM (GB),Avg Storage (GB),Avg CPU Tier,Touchscreen Ratio
2,2,49575.89,6.67,308.21,3.54,0.00
1,1,67827.05,10.63,1126.59,4.36,0.03
0,0,76739.23,9.51,413.33,4.14,1.00

In [58]:
market_cluster_profile["Segment Name"] = [
    "Budget Segment",
    "Mid-Range Segment",
    "Premium Segment"
]
market_cluster_profile

,Cluster,Avg Price,Avg RAM (GB),Avg Storage (GB),Avg CPU Tier,Touchscreen Ratio,Segment Name
2,2,49575.89,6.67,308.21,3.54,0.00,Budget Segment
1,1,67827.05,10.63,1126.59,4.36,0.03,Mid-Range Segment
0,0,76739.23,9.51,413.33,4.14,1.00,Premium Segment

#### conclusion

- The laptop market is strongly structured around pricing tiers. While technical specifications increase with price, premium features such as touchscreen capability significantly influence price positioning.
- This suggests that perceived user experience and design differentiation contribute meaningfully to market segmentation, beyond pure hardware performance metrics.
- The market-based clustering reveals a clear price-driven segmentation of laptops into three distinct economic tiers.

###### 0. Premium Segment

- Highest average price (~₹76K)

- Strong CPU tier and balanced RAM

- 100% touchscreen penetration

- This segment highlights premium user experience features, particularly touchscreen capability, which appears to command higher pricing even when raw specifications are comparable to the mid-range segment.

###### 1.Mid-Range Segment

- Moderate average price (~₹67K)

- Highest average storage capacity

- Strong CPU tier

- Minimal touchscreen presence

- This cluster represents performance-oriented productivity laptops, emphasizing storage and computing power over premium design elements.

###### 1.Budget Segment


- Lowest average price (~₹49K)

- Lowest RAM and CPU tier

- No touchscreen presence

- Moderate storage capacity

- This segment targets cost-sensitive users prioritizing affordability over advanced performance or premium features.

### compare hardware vs market segmentation:

In [59]:
pd.crosstab(
    df_market["hardware_cluster"],
    df_market["cluster"],
    normalize="index"
)

cluster                  0         1         2
hardware_cluster
0                 0.193182  0.355114  0.451705
1                 0.217391  0.608696  0.173913
2                 0.084532  0.338129  0.577338

### conclusion

- The cross-tabulation between hardware clusters and market clusters reveals that hardware identities do not map perfectly into pricing tiers.

- Certain hardware clusters are distributed across multiple price segments, indicating that similar technical configurations can exist at different price levels. This suggests that pricing is influenced not only by raw hardware specifications but also by factors such as brand positioning, design features, and perceived value.

- While market clustering shows strong price-based separation, hardware clustering reveals deeper technical differentiation that pricing alone does not fully capture.